/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#f0dbff",
        "primary-fixed": "#eaddff",
        "primary-container": "#7c3aed",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "surface-container-high": "#2b2835",
        "surface": "#181622",
        "on-surface": "#e6e0f0",
        "surface-dim": "#14121d",
        "text-primary": "#FFFFFF",
        "on-surface-variant": "#ccc3d8",
        "on-secondary-fixed-variant": "#6900b3",
        "on-secondary": "#490080",
        "on-tertiary": "#490081",
        "secondary-container": "#6f00be",
        "outline-variant": "#4a4455",
        "on-primary-fixed-variant": "#5a00c6",
        "on-primary-container": "#ede0ff",
        "secondary": "#ddb7ff",
        "on-primary": "#3f008e",
        "on-background": "#e6e0f0",
        "tertiary-container": "#844abe",
        "on-tertiary-fixed": "#2c0051",
        "on-secondary-container": "#d6a9ff",
        "secondary-fixed-dim": "#ddb7ff",
        "on-primary-fixed": "#25005a",
        "surface-container-low": "#1c1a26",
        "primary-fixed-dim": "#d2bbff",
        "text-secondary": "#B3B3C6",
        "tertiary-fixed": "#f0dbff",
        "error-container": "#93000a",
        "surface-container-highest": "#363340",
        "inverse-on-surface": "#312f3b",
        "surface-variant": "#363340",
        "surface-container-lowest": "#0f0d18",
        "on-tertiary-fixed-variant": "#62259b",
        "inverse-surface": "#e6e0f0",
        "outline": "#958da1",
        "tertiary-fixed-dim": "#ddb8ff",
        "primary": "#d2bbff",
        "tertiary": "#ddb8ff",
        "surface-tint": "#d2bbff",
        "on-secondary-fixed": "#2c0051",
        "surface-container": "#201e2a",
        "surface-bright": "#3a3744",
        "on-tertiary-container": "#f2e0ff",
        "glow-purple": "rgba(124, 58, 237, 0.4)",
        "background": "#14121d",
        "on-error": "#690005",
        "inverse-primary": "#732ee4"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "4px",
        "base": "8px",
        "margin-mobile": "20px",
        "margin-desktop": "48px",
        "gutter": "16px",
        "stack-md": "12px",
        "stack-lg": "24px",
        "pb-safe": "env(safe-area-inset-bottom, 20px)"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
